version: 2.1

jobs:
  fetch-and-deploy:
    docker:
      - image: cimg/node:14.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Execute fetchEarthquakeData.js file
          command: node fetchEarthquakeData.js
      - run:
          name: Configure Git
          command: |
            git config user.email "your-email@example.com"
            git config user.name "Your Name"
      - run:
          name: Commit and Push changes
          command: |
            git add now.js now.json
            git diff --quiet && git diff --staged --quiet || (git commit -m "Add generated files [skip ci]" && git push origin main)

workflows:
  version: 2
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 23 * * 3"  # 毎週水曜日の午後11時に実行（UTC時間）
          filters:
            branches:
              only:
                - main
    jobs:
      - fetch-and-deploy