
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      # JavaScriptファイルを実行して生成されたファイルを取得
      - run:
          name: Execute fetchEarthquakeData.js file
          command: node fetchEarthquakeData

      # 生成されたファイルをリポジトリに追加
      - persist_to_workspace:
          root: .
          paths:
            - now.js
            - now.json

  deploy:
    docker:
      - image: circleci/node:latest

    steps:
      - attach_workspace:
          at: .

      # ワークスペースから生成されたファイルを取得
      - run:
          name: Copy generated files
          command: cp now.js now.json ~/DockerProjects/js_fetchEarthquakeData

      # リポジトリに変更をコミットしてプッシュ
      - run:
          name: Commit and Push changes
          command: |
            git add now.js now.json;
            git commit -m "Add generated files";
            git push -u origin main
            
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
    triggers:
      - schedule:
          cron: "0 20 * * 4"  # 毎週木曜日の午後11時に実行
          filters:
            branches:
              only:
                - main